### ISSUE TITLE
[Feature Request] Collapse All 

### ISSUE THREAD

**Issue by pitecantropo** [mark-when/markwhen#101]
I've see the the docs refer that if we want to have groups/sections to be shown as collapsed we should indent with a space before 'group'.

I've done that for all groups but see everything expanded when opening on vscode. 

Notwithstanding the issue would be nice to have a 'Collapse All' button.

This project is really awesome. Thanks for all the hardwork.

**Comment by kochrt** [comment]
While I haven't yet fixed the initially collapsed group problem (in vscode anyway), I have added collapse all/expand all buttons in 1.3.1:

<img width="176" alt="Screen Shot 2023-01-27 at 10 30 35 AM" src="https://user-images.githubusercontent.com/10823320/215124355-5d35e10d-6dd1-4953-9a9c-6905ce847f41.png">

And thank you for the kind words, I'm glad you enjoy it!

**Comment by pitecantropo** [comment]
That is really cool (and he. Thanks for making time for it.
Seeing a change of text placement from 1.30 to 1.31. which kinda breaks visibility. The text in the latter is at the bottom of the item instead of to the right of it.


1.31
![image](https://user-images.githubusercontent.com/4513487/215137400-84b615b0-e1f8-40f7-84ec-f76664f19c7a.png)


1.30
![image](https://user-images.githubusercontent.com/4513487/215137449-08a9c026-49cc-483f-b3a0-5c19e80e950d.png)


Thanks again!

**Comment by kochrt** [comment]
Yikes that doesn't look good. Can you paste the text that you're using? I can't seem to be able to reproduce it

**Comment by pitecantropo** [comment]
Can't  replicate as well  now :X .
Not if an issue on vsCode. Will let you know if i see the behavior again.

Anyway. All is good now.
Thanks a mil.

**Comment by kochrt** [comment]
Well let's hope we never see it again!
