### ISSUE TITLE
[Feature Request] horizontal lines (like now)

### ISSUE THREAD

**Issue by AlexErmer** [mark-when/markwhen#109]
first of all, great work! I use the timeline to plan, track and review my projects.

I would like to have an option to define a date which is marked with a visible horizontal line. My usecase would be the defined deadline of an project to know exactly "ok, thats what we are able to do in time, and that will fail, or has to be done afterwards, maybe in a following project."

**Comment by kochrt** [comment]
So there's the `#era` or `#milestone` tags, which will draw a **vertical** line (like the now line), but there's nothing for horizontal... You can see the `#milestone` example on the [example timeline here](https://markwhen.com/example?page=9&view=Timeline).

Apparently I missed adding those to the documentation. Anyway as far as a horizontal line goes, you could maybe define a `section`? That extends across the timeline horizontally.

**Comment by AlexErmer** [comment]
oh shame on me.. i mixed up horizontal with vertical.. `#milestone` is exactly what I was looking for.

Thanks again for the great work! i'll close this one.
