### ISSUE TITLE
Zoom to Smaller and Larger Timescales

### ISSUE THREAD

**Issue by simc-pk** [mark-when/markwhen#49]
This tool is great for timelines that are days/months/years long, but unless I'm missing something it falls short when we move to minutes/seconds/milliseconds.  I'm trying to diagram out a phone hunt group and the entire thing takes place in a span of 45 seconds, with actions typically lasting anywhere from 5 to 15 seconds and even at the strongest zoom level, it's still zoomed out too far to be useful.

![image](https://user-images.githubusercontent.com/84403152/175353462-59535168-2ffe-49eb-a949-927cb0a21380.png)

**Comment by simc-pk** [comment]
Quick turnaround!  It's an improvement, but the times on the timeline at that top are all cluttered and overlay each other making them unusable.

![image](https://user-images.githubusercontent.com/84403152/175568079-20c34285-fd6b-45e9-849e-a706ff616405.png)

**Comment by simc-pk** [comment]
I should also mention that the minimap seems to be unusable and it might be related to the zoom levels.  I didn't realize until I loaded one of your example timelines that it wasn't entirely broken.  As it is now, it's extremely difficult to find specific points in time for a timeline that is focused on briefer intervals and a functioning minimap would go a long way to helping alleviate that.  I've been zooming by small amounts and then horizontally scrolling until I find my events -- rinse and repeat.  The most useful feature regarding zooming would be to be able to zoom to capture the entire length of a section or group on the timeline to eliminate the need for manual zooming in most cases.

sample code --
```
title: Front Door Hunt Group

#COLOR_DOORBELL_HUNT: #d336b1
#COLOR_DOORBELL_HUNT_2: #D35715
#COLOR_DOORBELL_HUNT_3: #17a14c

section Overall
2022-06-23T13:30:00Z to 2022-06-23T13:30:00Z: Doorbell Pressed

group DOORBELL HUNT #COLOR_DOORBELL_HUNT
12 seconds: Jim, Bob, Darrell
endgroup

group DOORBELL HUNT 2 #COLOR_DOORBELL_HUNT_2
12 seconds: Jim, Bob, Darrell, Alice 
endgroup

group DOORBELL HUNT 3 #COLOR_DOORBELL_HUNT_3
33 seconds: Veronica, Duane, Allison

endsection
```

**Comment by sujan-s** [comment]
I am using markwhen for marking events for a novel I’m working on—it’s a fantastic life-saver!

@kochrt  What would be useful is zooming out quite a lot—my timeline is 12,000 years long, and this introduces a LOT of scroll, even on my widescreen monitor. A “fit-to-width” as the minimum zoom-level could be useful.

**Comment by aronkvh** [comment]
I'd use Markwhen for creating a timeline of events for studying, so I have the opposite problem: I'd like zoom really really out, for ex. see 1500-2000 at once
