### ISSUE TITLE
Can't subscribe / process Stripe payment due to cross-origin iframe security error

### ISSUE THREAD

**Issue by michealrm** [mark-when/markwhen#90]
Hello,

When trying to pay for a monthly subscription, I am getting an error.

Steps to reproduce

- Open MarkWhen website (this bug is reproducing for me on Chrome, Safari, and Firefox)
- Open Shared tab
- Log in
- Enter email and payment info
- Select personal plan
- Enter payment info
- Click Subscribe button
- There are no changes on the UI and an error message shows in the console

Blocked a frame with origin "https://js.stripe.com" from accessing a frame with origin "https://markwhen.com". Protocols, domains, and ports must match.
Global Code — inject.js:669

**Comment by kochrt** [comment]
Oof sorry about that, looking into it

**Comment by kochrt** [comment]
Can you try it again? I pushed some changes that should hopefully have taken care of it. If it still doesn't work let me know.

**Comment by michealrm** [comment]
Yup, I was able to subscribe! Got the payment confirmation e-mail.

Although the error still appeared in the console and after the button loaded on Submitting, it just changed back to Submit, so the only way that I knew the payment was successful was by checking my e-mail and refreshing the page.

Additionally, I'm seeing the Subscription since 1/20/1970. Despite today being 12/29 and then of course the year.

If you'd like I can create separate issues for these?

**Comment by kochrt** [comment]
That would be great, if you don't mind! 

Sorry for the less than pleasant onboarding experience 😞. If you notice other issues or have suggestions please continue to let me know!

**Comment by michealrm** [comment]
Sounds good, will do. Thanks for the quick response time on this issue. And thank you for building this great project (hence the subscription)!
