### ISSUE TITLE
Collapsing repeating events into one line

### ISSUE THREAD

**Issue by Robert-M-Muench** [mark-when/markwhen#96]
In project planning, this is a pretty common pattern:

<img width="836" alt="image" src="https://user-images.githubusercontent.com/1826391/211149790-9d0d5f14-0611-44ce-8e7c-df98d76fd6ab.png">

However, this requires a lot of vertical space when you add the plan to some documents.

Much better would be a repeating event type, which shows all dots on one line and only shows the event text once at the end.

**Comment by Robert-M-Muench** [comment]
Here is an example of a *management level* plan:

![image](https://user-images.githubusercontent.com/1826391/211151480-7ed09a50-2ce0-4935-9270-902d443a3e3c.png)

That's a handy visualization most tools can't accomplish.

**Comment by kochrt** [comment]
Hi Robert, I appreciate the feature request (and the helpful screenshots)!

I just added support for [recurring events](https://docs.markwhen.com/syntax/dates-and-ranges.html#recurring-events), which might be able to accomplish some of what you're looking for.

I (kind of) recreated your first example to reduce the `Q&A`s to two lines (you'd have to massage it to get it to be what you want, also I am just now noticing a bug where relative dates aren't referring to the end of a recurring event):

```
!nippas 1 week - 11 weeks:
!nippas 2 weeks - 1 day every week x4: Q&A
2 weeks - 1 day every 2 weeks x3: Q&A
```

<img width="602" alt="Screen Shot 2023-01-18 at 6 23 34 PM" src="https://user-images.githubusercontent.com/10823320/213317274-ba1bf1b0-04d5-4572-a885-57e0b991f69b.png">

There is another [request](https://github.com/mark-when/markwhen/issues/79) similar to recurring events that is specifying multiple ranges for the same event. That's coming soon, so if recurring isn't what you want, hopefully multiple event ranges will help.

Meanwhile, you might also try [initially collapsed groups](https://docs.markwhen.com/syntax/groups-and-sections.html):
> If you want an event group to start out collapsed, indent the group line definition.

```
!nippas 1 week - 11 weeks:
 group Q&A
!nippas 2 weeks - 1 day every week x4: Q&A
5 weeks - 1 day every 2 weeks x3: Q&A
```
<img width="384" alt="Screen Shot 2023-01-18 at 6 34 18 PM" src="https://user-images.githubusercontent.com/10823320/213318370-dbb1479b-3add-457f-ba96-3503b185b490.png">
