### ISSUE TITLE
Update example timeline (on fresh start)

### ISSUE THREAD

**Issue by JulienMaille** [mark-when/markwhen#98]
I have 2 questions regarding the dummy projects one can see the first time they browse https://markwhen.com/
- *Life timeline exam*: tasks still use the now removed google photo image format.
- *Project planning example*: it's not clear if the 3 projects are parallel or nested. According to the display, they are nested. Are some `endGroup` keywords missing?

**Comment by kochrt** [comment]
Yes they are outdated. 

Google photos links are deprecated and the project sections should not be nested like they are.

I think the stuff in the readme needs to be updated too, it's on my list

**Comment by JulienMaille** [comment]
Thanks! I think it helps with user onboarding.
Do you plan to have one image in the examples?

**Comment by kochrt** [comment]
Yeah I think I should do that and have an example (if possible) of most features that markwhen supports

**Comment by kochrt** [comment]
I updated the example timeline and also added it at [markwhen.com/example](https://markwhen.com/example), let me know what you think

**Comment by JulienMaille** [comment]
Sorry for not answering faster. The new example breakdown is a very good idea. Maybe you could add one tab with examples for images embedding?
